const express = require('express');
const customerAuthRoutes = require('./customerAuthRoutes');
const adminAuthRoutes = require('./adminAuthRoutes');
const layoutRoutes = require('./layoutRoutes');
const homepageRoutes = require('./homepageRoutes');
const productRoutes = require('./productRoutes');
const giftSetRoutes = require('./giftSetRoutes');
const seasonalCollectionRoutes = require('./seasonalCollectionRoutes');
const reviewRoutes = require('./reviewRoutes');
const testimonialRoutes = require('./testimonialRoutes');
const newsletterRoutes = require('./newsletterRoutes');
const orderRoutes = require('./orderRoutes');
const addressRoutes = require('./addressRoutes');
const wishlistRoutes = require('./wishlistRoutes');
const profileRoutes = require('./profileRoutes');
const notificationRoutes = require('./notificationRoutes');
const contactRoutes = require('./contactRoutes');
const adminDashboardRoutes = require('./adminDashboardRoutes');
const adminProductRoutes = require('./adminProductRoutes');
const adminCollectionRoutes = require('./adminCollectionRoutes');
const adminFeaturedCollectionRoutes = require('./adminFeaturedCollectionRoutes');
const adminFragranceFamilyRoutes = require('./adminFragranceFamilyRoutes');
const adminGiftSetRoutes = require('./adminGiftSetRoutes');
const adminSeasonalCollectionRoutes = require('./adminSeasonalCollectionRoutes');
const adminOrderRoutes = require('./adminOrderRoutes');
const adminCustomerRoutes = require('./adminCustomerRoutes');
const adminReviewRoutes = require('./adminReviewRoutes');
const adminNewsletterRoutes = require('./adminNewsletterRoutes');
const adminInventoryRoutes = require('./adminInventoryRoutes');
const adminReportsRoutes = require('./adminReportsRoutes');
const adminNotificationRoutes = require('./adminNotificationRoutes');
const adminContactRoutes = require('./adminContactRoutes');
const adminHomepageRoutes = require('./adminHomepageRoutes');
const adminTestimonialRoutes = require('./adminTestimonialRoutes');
const adminWebsiteContentRoutes = require('./adminWebsiteContentRoutes');
const adminSettingsRoutes = require('./adminSettingsRoutes');
const adminEmailTemplateRoutes = require('./adminEmailTemplateRoutes');
const adminRoleRoutes = require('./adminRoleRoutes');
const adminActivityLogRoutes = require('./adminActivityLogRoutes');
const adminBackupRoutes = require('./adminBackupRoutes');
const adminSupplierRoutes = require('./adminSupplierRoutes');
const adminPurchaseRoutes = require('./adminPurchaseRoutes');
const adminPaymentRoutes = require('./adminPaymentRoutes');
const adminExpenseRoutes = require('./adminExpenseRoutes');
const adminReturnRoutes = require('./adminReturnRoutes');

const router = express.Router();

router.use('/customer/auth', customerAuthRoutes);
router.use('/admin/auth', adminAuthRoutes);
router.use('/layout', layoutRoutes);
router.use('/homepage', homepageRoutes);
router.use('/products', productRoutes);
router.use('/gift-sets', giftSetRoutes);
router.use('/seasonal-collections', seasonalCollectionRoutes);
router.use('/reviews', reviewRoutes);
router.use('/testimonials', testimonialRoutes);
router.use('/newsletter', newsletterRoutes);
router.use('/customer/orders', orderRoutes);
router.use('/customer/addresses', addressRoutes);
router.use('/customer/wishlist', wishlistRoutes);
router.use('/customer/profile', profileRoutes);
router.use('/customer/notifications', notificationRoutes);
router.use('/contact', contactRoutes);
router.use('/admin/dashboard', adminDashboardRoutes);
router.use('/admin/products', adminProductRoutes);
router.use('/admin/collections', adminCollectionRoutes);
router.use('/admin/featured-collections', adminFeaturedCollectionRoutes);
router.use('/admin/fragrance-families', adminFragranceFamilyRoutes);
router.use('/admin/gift-sets', adminGiftSetRoutes);
router.use('/admin/seasonal-collections', adminSeasonalCollectionRoutes);
router.use('/admin/orders', adminOrderRoutes);
router.use('/admin/customers', adminCustomerRoutes);
router.use('/admin/reviews', adminReviewRoutes);
router.use('/admin/newsletter', adminNewsletterRoutes);
router.use('/admin/inventory', adminInventoryRoutes);
router.use('/admin/reports', adminReportsRoutes);
router.use('/admin/notifications', adminNotificationRoutes);
router.use('/admin/messages', adminContactRoutes);
router.use('/admin/homepage', adminHomepageRoutes);
router.use('/admin/testimonials', adminTestimonialRoutes);
router.use('/admin/website-content', adminWebsiteContentRoutes);
router.use('/admin/settings', adminSettingsRoutes);
router.use('/admin/email-templates', adminEmailTemplateRoutes);
router.use('/admin/users', adminRoleRoutes);
router.use('/admin/activity-logs', adminActivityLogRoutes);
router.use('/admin/backup', adminBackupRoutes);
router.use('/admin/suppliers', adminSupplierRoutes);
router.use('/admin/purchases', adminPurchaseRoutes);
router.use('/admin/payments', adminPaymentRoutes);
router.use('/admin/expenses', adminExpenseRoutes);
router.use('/admin/returns', adminReturnRoutes);

module.exports = router;
